In [8]:
import folium, json
import pandas as pd
import geopandas as gpd
import datetime as dt

In [9]:
# Prepare geojson
health_boards = gpd.read_file('data-ingest/local_health_boards.geojson')[['objectid', 'lhb16nm', 'geometry']]
health_boards.columns = ['objectid', 'health_board', 'geometry']
health_boards.head()

,objectid,health_board,geometry
0,1,Betsi Cadwaladr University Health Board,"MULTIPOLYGON (((-3.32218 53.35687, -3.32271 53..."
1,2,Powys Teaching Health Board,"POLYGON ((-3.15512 52.89799, -3.15502 52.89805..."
2,3,Hywel Dda University Health Board,"MULTIPOLYGON (((-3.91124 52.56135, -3.91194 52..."
3,4,Abertawe Bro Morgannwg University Health Board,"MULTIPOLYGON (((-3.86318 51.80970, -3.86349 51..."
4,5,Cwm Taf University Health Board,"POLYGON ((-3.40254 51.82458, -3.40252 51.82460..."

In [10]:
beds = pd.read_csv('data-ingest/data/beds_percent_covid.csv', usecols = ['date', 'health_board', 'percent_beds_in_use_covid'])
beds.head()

,date,health_board,percent_beds_in_use_covid
0,2020-04-01,Betsi Cadwaladr University Health Board,0.082817
1,2020-04-01,Hywel Dda University Health Board,0.083812
2,2020-04-01,Abertawe Bro Morgannwg University Health Board,0.108946
3,2020-04-01,Cardiff and Vale University Health Board,0.125177
4,2020-04-01,Cwm Taf University Health Board,0.126117

In [11]:
beds['date'] = pd.to_datetime(beds['date'])
beds.head()

,date,health_board,percent_beds_in_use_covid
0,2020-04-01,Betsi Cadwaladr University Health Board,0.082817
1,2020-04-01,Hywel Dda University Health Board,0.083812
2,2020-04-01,Abertawe Bro Morgannwg University Health Board,0.108946
3,2020-04-01,Cardiff and Vale University Health Board,0.125177
4,2020-04-01,Cwm Taf University Health Board,0.126117

In [12]:
# the situation leading up to the firebreak (two weeks before)
firebreak = beds[beds['date'] >= dt.datetime.strptime("2020-09-01", "%Y-%m-%d")]
firebreak.head()

,date,health_board,percent_beds_in_use_covid
1355,2020-09-01,Betsi Cadwaladr University Health Board,0.036585
1356,2020-09-01,Hywel Dda University Health Board,0.010055
1357,2020-09-01,Abertawe Bro Morgannwg University Health Board,0.012403
1358,2020-09-01,Cardiff and Vale University Health Board,0.040791
1359,2020-09-01,Cwm Taf University Health Board,0.027921

In [13]:
joined_df = beds.merge(health_boards[['health_board', 'geometry']], how='left', on=['health_board'])
joined_df.head()

,date,health_board,percent_beds_in_use_covid,geometry
0,2020-04-01,Betsi Cadwaladr University Health Board,0.082817,"MULTIPOLYGON (((-3.32218 53.35687, -3.32271 53..."
1,2020-04-01,Hywel Dda University Health Board,0.083812,"MULTIPOLYGON (((-3.91124 52.56135, -3.91194 52..."
2,2020-04-01,Abertawe Bro Morgannwg University Health Board,0.108946,"MULTIPOLYGON (((-3.86318 51.80970, -3.86349 51..."
3,2020-04-01,Cardiff and Vale University Health Board,0.125177,"MULTIPOLYGON (((-3.16373 51.56051, -3.16401 51..."
4,2020-04-01,Cwm Taf University Health Board,0.126117,"POLYGON ((-3.40254 51.82458, -3.40252 51.82460..."

In [14]:
# convert date to seconds for folium
joined_df['date_sec'] = pd.to_numeric(joined_df['date']) / 10**9
joined_df['date_sec'] = joined_df['date_sec'].astype(int).astype(str)
# convert proportion to percentage for ease of reading
joined_df['percent_beds_in_use_covid'] = joined_df['percent_beds_in_use_covid']*100
joined_df.head()

,date,health_board,percent_beds_in_use_covid,geometry,date_sec
0,2020-04-01,Betsi Cadwaladr University Health Board,8.281734,"MULTIPOLYGON (((-3.32218 53.35687, -3.32271 53...",1585699200
1,2020-04-01,Hywel Dda University Health Board,8.381171,"MULTIPOLYGON (((-3.91124 52.56135, -3.91194 52...",1585699200
2,2020-04-01,Abertawe Bro Morgannwg University Health Board,10.894597,"MULTIPOLYGON (((-3.86318 51.80970, -3.86349 51...",1585699200
3,2020-04-01,Cardiff and Vale University Health Board,12.517680,"MULTIPOLYGON (((-3.16373 51.56051, -3.16401 51...",1585699200
4,2020-04-01,Cwm Taf University Health Board,12.611718,"POLYGON ((-3.40254 51.82458, -3.40252 51.82460...",1585699200

In [15]:
import branca.colormap as cm
# prepare folium colours
min_colour = min(joined_df['percent_beds_in_use_covid'])
max_colour = max(joined_df['percent_beds_in_use_covid'])
cmap = cm.LinearColormap(
    ['#DAE3E7', '#9C528B'],
    vmin=min_colour, vmax=max_colour
)
joined_df['colour'] = joined_df['percent_beds_in_use_covid'].map(cmap)

In [ ]:
# create styledict for folium
hb_list = joined_df['health_board'].unique().tolist()
hb_idx = range(len(hb_list))

style_dict = {}
for i in hb_idx:
    hb = hb_list[i]
    result = joined_df[joined_df['health_board'] == hb]
    inner_dict = {}
    for _, r in result.iterrows():
        inner_dict[r['date_sec']] = {'color': r['colour'], 'opacity': 1, 'outline': 'black'}
    style_dict[str(i)] = inner_dict

In [ ]:
from folium.plugins import TimeSliderChoropleth

slider_map = folium.Map(tiles='cartodbpositron', location=[52.5, -4], zoom_start=7)

ts = TimeSliderChoropleth(
    name='timeSlider',
    overlay = True,
    data=health_boards['geometry'].to_json(),
    styledict=style_dict,

).add_to(slider_map)

# add health board borders for clarity
borders = folium.Choropleth(
    geo_data=health_boards.to_json(),
    fill_color=None,
    line_color = 'black',
    fill_opacity=0,
    line_opacity=0.8,
).add_to(slider_map)

borders.geojson.add_child(
    folium.features.GeoJsonTooltip(['health_board'])
)

cm = cmap.add_to(slider_map)
cmap.caption = "Percentage of hospital beds occupied by COVID-19 patients"
folium.LayerControl().add_to(slider_map)
slider_map.save('visualisations/admissions_allhb_map.html')
slider_map

In [ ]:
import branca.colormap as cm
cm.linear